_BASE_: "./swinl_coco.yaml"
MODEL:
  WEIGHTS: "pretrained/mdqe_swinl_patch4_window24_384_22k_coco_bs8_3x_f1.pth"
  MDQE:
    NUM_CLASSES: 25
    WINDOW_INTER_FRAME_ASSOCIATION: 5
    CLIP_STRIDE: 1
    SAMPLING_FRAME_NUM_TEST: 2
    MAX_NUM_INSTANCES: 120
    WINDOW_FRAME_NUM_TEST: 20
    MERGE_ON_CPU: True
    APPLY_CLS_THRES: 0.1
DATASETS:
  DATASET_RATIO: [ 0.75, 1.0 ]
  TRAIN: ("coco2ovis_train", "ytvis_ovis_train")
  TEST: ("ytvis_ovis_val",)  # during training, use TEST: ("ytvis_ovis_dev",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00005
  STEPS: (20000, )
  MAX_ITER: 24000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  FORMAT: "RGB"
  SAMPLING_FRAME_NUM: 2
  SAMPLING_FRAME_RANGE: 7
  PRETRAIN_FRAME_NUM: 1
  AUGMENTATIONS: []
  RANDOM_FLIP: "flip_by_clip"
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736)  # for clip length <= 2
  MAX_SIZE_TRAIN: 1024
#  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512, 544)  # for clip length > 2
#  MAX_SIZE_TRAIN: 960
  MIN_SIZE_TEST: 480
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.8, 0.8]
  PSEUDO:
    AUGMENTATIONS: [ 'rotation' ]
    MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
    MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736)  # for clip length <= 2
    MAX_SIZE_TRAIN: 1024
#    MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512, 544)  # for clip length > 2
#    MAX_SIZE_TRAIN: 960
    CROP:
      ENABLED: True
      TYPE: "absolute_range"
      SIZE: (384, 600)
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 15
OUTPUT_DIR: output/ovis/mdqe_swinl_ovis_bs8_f2/
